### ISSUE TITLE
Add builtin proxy settings

### ISSUE THREAD

**Issue by Yuan-Quan** [ImpactDevelopment/Installer#123]
**Problem**
Internet connection in China is kind of broken, add VPN software seems can't catch the traffic from Java programs.
Result in the installer almost unusable in China. Several friends of mine have complained that they can't install impact.

**Describe the solution you'd like**
Add an option to use proxy.

**A ways I can get it working in China**
Use cfw-tap virtual adapter to route all traffic into VPN software.

**Additional context**
Console output:
```bash
$ java -jar ./ImpactInstaller-0.9.4.jar
                   ...
DOWNLOADING https://github.com/ImpactDevelopment/ImpactReleases/releases/download/4.9.1-1.12.2/Impact-4.9.1-1.12.2.json
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.
        ...
Trying some hacks to get this to load!
Undoing hacks!
java.lang.NullPointerException
        at java.util.Hashtable.put(Unknown Source)
        at java.util......
        ...

```

**Comment by chinese-wzq** [comment]
It took me over 6 hours to try again and again at least 80 times.We chinese really need the function.
