### ISSUE TITLE
0.7.0 launcher does not open

### ISSUE THREAD

**Issue by retreat896** [ImpactDevelopment/Installer#74]
When opening the installer exe and jar file both do not give any output and stop immediately.
they show in command prompt and instantly disappear.

**Comment by leijurv** [comment]
Can you try running with `java -jar`?

**Comment by leijurv** [comment]
What's the stacktrace

**Comment by leijurv** [comment]
Issue was:

```
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/krisa/Downloads/installer-0.7.0.jar
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPath.parse(Unknown Source)
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.nio.file.Paths.get(Unknown Source)
        at io.github.ImpactDevelopment.installer.Installer.getJarPath(Unknown Source)
        at io.github.ImpactDevelopment.installer.Installer.main(Unknown Source)
```

**Comment by leijurv** [comment]
Fixed by https://github.com/ImpactDevelopment/Installer/commit/82e12e0e99dbd39c8ee86a9f40f676014b733d2e
