### ISSUE TITLE
crash on start cant open

### ISSUE THREAD

**Issue by shadowbunshin** [ImpactDevelopment/Installer#90]
[latest.log](https://github.com/ImpactDevelopment/Installer/files/4410304/latest.log)
i tried 4.8.2 and 4.8.3 with clean install
Mixin apply failed mixins.impact.json:accessor.AccessorPlayerEntity

**Comment by StudyPony** [comment]
crash without showing the game windows at all, too.
i tried another minecraft launcher(HMCL) and got these logs.

```
Command: "C:\\Program Files\\Java\\jdk1.8.0_241\\jre\\bin\\java.exe" -Dminecraft.client.jar=.minecraft\versions\1.12.2\1.12.2.jar -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx2048m -Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Djava.library.path=C:\Users\Niamia\AppData\Roaming\.minecraft\versions\1.12.2-Impact_4.8.3\1.12.2-Impact_4.8.3-natives -Dminecraft.launcher.brand=HMCL -Dminecraft.launcher.version=3.2.149 -cp C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\com\github\ImpactDevelopment\Impact\4.8.3-1.12.2\Impact-4.8.3-1.12.2.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\cabaletta\baritone-api\1.2.10\baritone-api-1.2.10.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\com\github\ImpactDevelopment\SimpleTweaker\1.2\SimpleTweaker-1.2.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\com\github\ZeroMemes\Alpine\1.8\Alpine-1.8.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\net\impactclient\feather\1.0-2.9\feather-1.0-2.9.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\net\jodah\typetools\0.5.0\typetools-0.5.0.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\io\jsonwebtoken\jjwt-api\0.10.7\jjwt-api-0.10.7.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\io\jsonwebtoken\jjwt-impl\0.10.7\jjwt-impl-0.10.7.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\io\jsonwebtoken\jjwt-orgjson\0.10.7\jjwt-orgjson-0.10.7.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\org\spongepowered\mixin\0.7.11-SNAPSHOT\mixin-0.7.11-SNAPSHOT.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\com\github\ImpactDevelopment\Installer\0.7.5\Installer-0.7.5.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\club\minnced\java-discord-rpc\2.0.1\java-discord-rpc-2.0.1.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper\1.12\launchwrapper-1.12.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\org\json\json\20190722\json-20190722.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-all\5.2\asm-all-5.2.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\club\minnced\discord-rpc-release\v3.3.0\discord-rpc-release-v3.3.0.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\com\mojang\patchy\1.1\patchy-1.1.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.1.9.Final\netty-all-4.1.9.Final.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\21.0\guava-21.0.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.5\commons-io-2.5.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.8.0\gson-2.8.0.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.5.25\authlib-1.5.25.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\com\mojang\realms\1.10.22\realms-1.10.22.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\it\unimi\dsi\fastutil\7.1.0\fastutil-7.1.0.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.8.1\log4j-api-2.8.1.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.8.1\log4j-core-2.8.1.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\libraries\com\mojang\text2speech\1.10.3\text2speech-1.10.3.jar;C:\Users\Niamia\AppData\Roaming\.minecraft\versions\1.12.2\1.12.2.jar net.minecraft.launchwrapper.Launch --username TaravenX --version "HMCL 3.2.149" --gameDir C:\Users\Niamia\AppData\Roaming\.minecraft --assetsDir C:\Users\Niamia\AppData\Roaming\.minecraft\assets --assetIndex 1.12 --uuid 19db1bfd9d9a4941a2f876f93ce5b5c7 --accessToken eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxN2JhNDgxMzAzMjY0MjgzYWNlNWM2Zjc3MzI4NWVjZiIsInlnZ3QiOiIxNTgwNGJhZmQzNmQ0NTRlYTU4YTA3NDYzYmYxMzU0MSIsInNwciI6IjE5ZGIxYmZkOWQ5YTQ5NDFhMmY4NzZmOTNjZTViNWM3IiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE1ODY1NzQ4NTAsImlhdCI6MTU4NjQwMjA1MH0.2jWZDf6h94umrmz00bRwAEKunJnaDFJM_X8r-4-IEdw --userType mojang --tweakClass clientapi.load.ClientTweaker --tweakClass baritone.launch.BaritoneTweaker
[11:14:29] [main/INFO]: Loading tweak class name clientapi.load.ClientTweaker

[11:14:29] [main/INFO]: Using primary tweak class name clientapi.load.ClientTweaker

[11:14:29] [main/INFO]: Loading tweak class name baritone.launch.BaritoneTweaker

[11:14:29] [main/INFO]: Calling tweak class clientapi.load.ClientTweaker

[11:14:29] [main/INFO]: Injecting into ClassLoader

[11:14:29] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/Niamia/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar Service=LaunchWrapper Env=UNKNOWN

[11:14:29] [main/INFO]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.

[11:14:29] [main/INFO]: Initialized Mixin bootstrap

[11:14:29] [main/INFO]: Setup Mixin Environment

[11:14:29] [main/INFO]: Compatibility level set to JAVA_8

[11:14:29] [main/ERROR]: Mixin config mixins.impact.json does not specify "minVersion" property

[11:14:29] [main/INFO]: Loaded Mixin Configurations

[11:14:29] [main/INFO]: Calling tweak class baritone.launch.BaritoneTweaker

[11:14:29] [main/ERROR]: Mixin config mixins.baritone.json does not specify "minVersion" property

[11:14:29] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker

[11:14:29] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker

[11:14:29] [main/ERROR]: Unable to launch

java.lang.ClassNotFoundException: net.minecraft.client.main.Main

	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]

	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_241]

	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241]

	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_241]

	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_241]

	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]

	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

Caused by: java.lang.NullPointerException

	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]

	... 6 more

```
